package ai.z.openapi.service.deserialize;

import ai.z.openapi.service.deserialize.knowledge.document.DocumentDataDeserializer;
import ai.z.openapi.service.deserialize.knowledge.document.DocumentDataFailInfoDeserializer;
import ai.z.openapi.service.deserialize.knowledge.document.DocumentFailedInfoDeserializer;
import ai.z.openapi.service.deserialize.knowledge.document.DocumentObjectDeserializer;
import ai.z.openapi.service.deserialize.knowledge.document.DocumentPageDeserializer;
import ai.z.openapi.service.deserialize.knowledge.document.DocumentSuccessInfoDeserializer;
import ai.z.openapi.service.deserialize.tools.ChoiceDeltaDeserializer;
import ai.z.openapi.service.deserialize.tools.ChoiceDeltaToolCallDeserializer;
import ai.z.openapi.service.deserialize.tools.SearchChatMessageDeserializer;
import ai.z.openapi.service.deserialize.tools.SearchIntentDeserializer;
import ai.z.openapi.service.deserialize.tools.SearchRecommendDeserializer;
import ai.z.openapi.service.deserialize.tools.SearchResultDeserializer;
import ai.z.openapi.service.deserialize.tools.WebSearchChoiceDeserializer;
import ai.z.openapi.service.deserialize.tools.WebSearchMessageDeserializer;
import ai.z.openapi.service.deserialize.tools.WebSearchMessageToolCallDeserializer;
import ai.z.openapi.service.deserialize.tools.WebSearchProDeserializer;
import ai.z.openapi.service.knowledge.document.DocumentData;
import ai.z.openapi.service.knowledge.document.DocumentDataFailInfo;
import ai.z.openapi.service.knowledge.document.DocumentFailedInfo;
import ai.z.openapi.service.knowledge.document.DocumentObject;
import ai.z.openapi.service.knowledge.document.DocumentPage;
import ai.z.openapi.service.knowledge.document.DocumentSuccessInfo;
import ai.z.openapi.service.model.ChatFunctionCall;
import ai.z.openapi.service.model.ChatMessage;
import ai.z.openapi.service.model.Choice;
import ai.z.openapi.service.model.Delta;
import ai.z.openapi.service.model.ModelData;
import ai.z.openapi.service.model.ToolCalls;
import ai.z.openapi.service.tools.ChoiceDelta;
import ai.z.openapi.service.tools.ChoiceDeltaToolCall;
import ai.z.openapi.service.tools.SearchChatMessage;
import ai.z.openapi.service.tools.SearchIntent;
import ai.z.openapi.service.tools.SearchRecommend;
import ai.z.openapi.service.tools.SearchResult;
import ai.z.openapi.service.tools.WebSearchChoice;
import ai.z.openapi.service.tools.WebSearchMessage;
import ai.z.openapi.service.tools.WebSearchMessageToolCall;
import ai.z.openapi.service.tools.WebSearchPro;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.module.SimpleModule;
import ai.z.openapi.service.assistant.AssistantChoice;
import ai.z.openapi.service.assistant.AssistantCompletion;
import ai.z.openapi.service.assistant.CompletionUsage;
import ai.z.openapi.service.assistant.ErrorInfo;
import ai.z.openapi.service.deserialize.assistant.AssistantChoiceDeserializer;
import ai.z.openapi.service.deserialize.assistant.AssistantCompletionDeserializer;
import ai.z.openapi.service.deserialize.assistant.CompletionUsageDeserializer;
import ai.z.openapi.service.deserialize.assistant.ErrorInfoDeserializer;
import ai.z.openapi.service.deserialize.embedding.EmbeddingDeserializer;
import ai.z.openapi.service.deserialize.embedding.EmbeddingResultDeserializer;
import ai.z.openapi.service.deserialize.image.ImageDeserializer;
import ai.z.openapi.service.deserialize.image.ImageResultDeserializer;
import ai.z.openapi.service.deserialize.knowledge.KnowledgeInfoDeserializer;
import ai.z.openapi.service.deserialize.knowledge.KnowledgePageDeserializer;
import ai.z.openapi.service.deserialize.knowledge.KnowledgeStatisticsDeserializer;
import ai.z.openapi.service.deserialize.knowledge.KnowledgeUsedDeserializer;
import ai.z.openapi.service.deserialize.videos.VideoObjectDeserializer;
import ai.z.openapi.service.deserialize.videos.VideoResultDeserializer;
import ai.z.openapi.service.embedding.Embedding;
import ai.z.openapi.service.embedding.EmbeddingResult;
import ai.z.openapi.service.image.Image;
import ai.z.openapi.service.image.ImageResult;
import ai.z.openapi.service.knowledge.KnowledgeInfo;
import ai.z.openapi.service.knowledge.KnowledgePage;
import ai.z.openapi.service.knowledge.KnowledgeStatistics;
import ai.z.openapi.service.knowledge.KnowledgeUsed;
import ai.z.openapi.service.model.params.CodeGeexContext;
import ai.z.openapi.service.videos.VideoObject;
import ai.z.openapi.service.videos.VideoResult;

public class MessageDeserializeFactory {

	public static ObjectMapper defaultObjectMapper() {
		ObjectMapper mapper = new ObjectMapper();
		mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
		mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
		mapper.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
		SimpleModule module = new SimpleModule();

		module.addDeserializer(ModelData.class, new ModelDataDeserializer());
		module.addDeserializer(Choice.class, new ChoiceDeserializer());
		module.addDeserializer(ChoiceDelta.class, new ChoiceDeltaDeserializer());
		module.addDeserializer(ChoiceDeltaToolCall.class, new ChoiceDeltaToolCallDeserializer());
		module.addDeserializer(SearchChatMessage.class, new SearchChatMessageDeserializer());
		module.addDeserializer(SearchIntent.class, new SearchIntentDeserializer());
		module.addDeserializer(SearchRecommend.class, new SearchRecommendDeserializer());
		module.addDeserializer(SearchResult.class, new SearchResultDeserializer());
		module.addDeserializer(WebSearchChoice.class, new WebSearchChoiceDeserializer());
		module.addDeserializer(WebSearchMessage.class, new WebSearchMessageDeserializer());
		module.addDeserializer(WebSearchMessageToolCall.class, new WebSearchMessageToolCallDeserializer());
		module.addDeserializer(WebSearchPro.class, new WebSearchProDeserializer());
		module.addDeserializer(VideoResult.class, new VideoResultDeserializer());
		module.addDeserializer(VideoObject.class, new VideoObjectDeserializer());
		module.addDeserializer(Image.class, new ImageDeserializer());
		module.addDeserializer(ImageResult.class, new ImageResultDeserializer());
		module.addDeserializer(KnowledgeInfo.class, new KnowledgeInfoDeserializer());
		module.addDeserializer(KnowledgeUsed.class, new KnowledgeUsedDeserializer());
		module.addDeserializer(KnowledgeStatistics.class, new KnowledgeStatisticsDeserializer());
		module.addDeserializer(KnowledgePage.class, new KnowledgePageDeserializer());
		module.addDeserializer(DocumentFailedInfo.class, new DocumentFailedInfoDeserializer());
		module.addDeserializer(DocumentObject.class, new DocumentObjectDeserializer());
		module.addDeserializer(DocumentSuccessInfo.class, new DocumentSuccessInfoDeserializer());
		module.addDeserializer(DocumentData.class, new DocumentDataDeserializer());
		module.addDeserializer(DocumentDataFailInfo.class, new DocumentDataFailInfoDeserializer());
		module.addDeserializer(DocumentPage.class, new DocumentPageDeserializer());
		module.addDeserializer(EmbeddingResult.class, new EmbeddingResultDeserializer());
		module.addDeserializer(Embedding.class, new EmbeddingDeserializer());
		module.addDeserializer(KnowledgeInfo.class, new KnowledgeInfoDeserializer());
		module.addDeserializer(AssistantChoice.class, new AssistantChoiceDeserializer());
		module.addDeserializer(AssistantCompletion.class, new AssistantCompletionDeserializer());
		module.addDeserializer(CompletionUsage.class, new CompletionUsageDeserializer());
		module.addDeserializer(ErrorInfo.class, new ErrorInfoDeserializer());
		mapper.registerModule(module);

		return mapper;
	}

}
